name: Build and Publish db-migrate

on:
  push:
    branches:
      - master    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 6.0.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '6.0.x'
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
      - name: Nuget Restore
        run: dotnet restore
      - name: Build dotnet-db-migrate
        run: dotnet build --configuration Release --no-restore
      - name: Package dotnet-db-migrate
        run: dotnet pack --configuration Release -o $GITHUB_WORKSPACE/artifacts
      - name: Publish dotnet-db-migrate to Nuget
        run: dotnet nuget push $GITHUB_WORKSPACE/artifacts/*.nupkg